import {defineConfig} from 'astro/config';
import UnoCSS from 'unocss/astro';
import compress from "astro-compress";
import critters from "astro-critters";
import image from "@astrojs/image";
import sitemap from '@astrojs/sitemap';


// https://astro.build/config
export default defineConfig({
  vite: {
    ssr: {
      external: ["svgo"]
    }
  },
  integrations: [sitemap(), image({
    // may be useful if your hosting provider allows caching between CI builds
    cacheDir: "./.cache/image"
  }), UnoCSS(), critters(), compress({
    css: false,
    html: {
      caseSensitive: true,
      collapseBooleanAttributes: true,
      collapseInlineTagWhitespace: false,
      collapseWhitespace: true,
      conservativeCollapse: false,
      continueOnParseError: false,
      customAttrAssign: [],
      customAttrCollapse: new RegExp("", "i"),
      customAttrSurround: [],
      customEventAttributes: [/^on[a-z]{3,}$/],
      decodeEntities: false,
      html5: true,
      ignoreCustomComments: [],
      ignoreCustomFragments: [],
      includeAutoGeneratedTags: true,
      keepClosingSlash: true,
      maxLineLength: null,
      minifyCSS: true,
      minifyJS: true,
      minifyURLs: false,
      preserveLineBreaks: false,
      preventAttributesEscaping: false,
      processConditionalComments: true,
      processScripts: [],
      quoteCharacter: "",
      removeAttributeQuotes: true,
      removeComments: true,
      removeEmptyAttributes: false,
      removeEmptyElements: false,
      removeOptionalTags: false,
      removeRedundantAttributes: false,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      removeTagWhitespace: true,
      sortAttributes: true,
      sortClassName: true,
      trimCustomFragments: false,
      useShortDoctype: false,
    },
    js: false,
    img: false,
    svg: false,
  })],
  site: 'https://www.digitalcanvas.com.br/'
});