# sample netlify.toml
[build]
  command = "yarn run build"
  publish = "dist"

# note: each of these fields are OPTIONAL
[dev]
  command = "yarn run dev" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser