[build.environment]
  NODE_VERSION = "18.17.1"


[build]
  publish = "dist"
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  functions = "functions/"

[dev]
  autoLaunch = true
  # command = "pnpm run dev"
  framework = "astro" # #custom
  command = "pnpm run dev"
  targetPort = 4321


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
