[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm build || ( npm install pnpm && pnpm build )"

[dev]
  autoLaunch = false
  command = "pnpm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
