[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  functions = "functions/"

[dev]
  autoLaunch = false
  # command = "pnpm run dev"
  framework = "#custom"
  targetPort = 3000
  command = "astro dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
